# Generated by Django 4.2.2 on 2023-06-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_task_comment_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task_id',
        ),
    ]
