# Generated by Django 4.2.2 on 2023-06-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comment_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tas_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
    ]
